---
# Tasks file for sublime-text

- name: import os specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: import os specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

# Install Package Control

- name: Check sublime Installed Package directory
  stat:
    path: "{{ sublime_installed_packages_dir }}"
  register: check_sublime_installed_packages_dir
  when: sublime_package_control

- name: Create Installed Package directory
  file:
    path: "{{ sublime_installed_packages_dir }}"
    state: directory
  when: sublime_package_control and check_sublime_installed_packages_dir.stat.exists == False

- name: Install package control for sublime
  get_url:
    url: "{{ sublime_package_control_url }}/Package%20Control.sublime-package"
    dest: "{{ sublime_installed_packages_dir }}/Package Control.sublime-package"
  when: sublime_package_control

# Install & Configure Sublime Text Packages

- name: Check sublime Package directory
  stat:
    path: "{{ sublime_packages_dir }}"
  register: check_sublime_packages_dir
  when: sublime_package_control

- name: Create Package directory
  file:
    path: "{{ sublime_packages_dir }}"
    state: directory
  when: sublime_package_control and check_sublime_packages_dir.stat.exists == False

- name: Install all sublime plugins
  git:
    repo: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('master') }}"
    dest: "{{ sublime_packages_dir }}"
    accept_hostkey: "yes"
  with_items: "{{ sublime_packages }}"
  when: sublime_package_control

# Install license key

- name: Check sublime Local directory
  stat:
    path: "{{ sublime_local_dir }}"
  register: check_sublime_local_dir
  when: sublime_license

- name: Create Local directory
  file:
    path: "{{ sublime_local_dir }}"
    state: directory
  when: sublime_license and check_sublime_local_dir.stat.exists == False

- name: Check licence key file location
  stat:
    path: "{{ sublime_license_path }}"
  register: check_sublime_license_key
  when: sublime_license

- name: Add license key
  lineinfile:
    path: "{{ sublime_license_path }}"
    line: "{{ sublime_license_key }}"
    state: present
    create: yes
  when: sublime_license and check_sublime_license_key.stat.exists == False




